# Generated by Django 5.0.6 on 2024-06-18 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_job_time_alter_job_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 18)),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.TimeField(default=datetime.time(11, 39, 32, 994187)),
        ),
    ]
