# Generated by Django 5.0.6 on 2024-06-18 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_job_date_alter_job_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.TimeField(default=datetime.time(11, 46, 33, 883336)),
        ),
    ]
