# Generated by Django 5.0.6 on 2024-06-18 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_job_date_alter_job_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='rescheduled',
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.TimeField(default=datetime.time(12, 37, 28, 8636)),
        ),
    ]
